### ISSUE TITLE
Some questions and comments for `function.h`

### ISSUE THREAD

**Issue by frederick-vs-ja** [StellarWarp/AutoDelegate#1]
https://github.com/StellarWarp/AutoDelegate/blob/aca3daab914712628bb76b68f6f09962dd91954d/src/delegate/function.h#L5

这里使用 `<assert.h>` 而非 `<cassert>` 有什么寓意吗。据我所知它们效果是一样的，使用 `<cassert>` 更一致一些。

https://github.com/StellarWarp/AutoDelegate/blob/aca3daab914712628bb76b68f6f09962dd91954d/src/delegate/function.h#L13
https://github.com/StellarWarp/AutoDelegate/blob/aca3daab914712628bb76b68f6f09962dd91954d/src/delegate/function.h#L233
此处的无名命名空间似乎是有害的。它会造成一些对象在不同翻译单元具有不同类型，并造成 ODR 违规。

https://github.com/StellarWarp/AutoDelegate/blob/aca3daab914712628bb76b68f6f09962dd91954d/src/delegate/function.h#L38-L42
https://github.com/StellarWarp/AutoDelegate/blob/aca3daab914712628bb76b68f6f09962dd91954d/src/delegate/function.h#L335-L340
这里可能应该使用 `::new(self) T(...)` 确保选择标准库提供的重载。后面有些地方已经加了 `::` 使用标准库版本了。
既然已经用了 `requires`，可以考虑使用 C++20 的 `construct_at`？

https://github.com/StellarWarp/AutoDelegate/blob/aca3daab914712628bb76b68f6f09962dd91954d/src/delegate/function.h#L67-L72
https://github.com/StellarWarp/AutoDelegate/blob/aca3daab914712628bb76b68f6f09962dd91954d/src/delegate/function.h#L366-L371

如果用户给自己的类重载了 `operator new`/`operator delete`，我们应该尊重用户的设定，还是一致地确保使用标准库版本的 `::operator new`/`::operator delete` 呢？

https://github.com/StellarWarp/AutoDelegate/blob/aca3daab914712628bb76b68f6f09962dd91954d/src/delegate/function.h#L74-L75
https://github.com/StellarWarp/AutoDelegate/blob/aca3daab914712628bb76b68f6f09962dd91954d/src/delegate/function.h#L373-L374
为什么移动函数没有 `noexcept`？另外可以考虑用下 `exchange`。

https://github.com/StellarWarp/AutoDelegate/blob/aca3daab914712628bb76b68f6f09962dd91954d/src/delegate/function.h#L97
https://github.com/StellarWarp/AutoDelegate/blob/aca3daab914712628bb76b68f6f09962dd91954d/src/delegate/function.h#L402
使用 `protected` 的意图是什么？难道是允许用户可以通过派生类和成员指针的方式 "hack" 到数据成员并直接修改吗？

https://github.com/StellarWarp/AutoDelegate/blob/aca3daab914712628bb76b68f6f09962dd91954d/src/delegate/function.h#L153-L160
https://github.com/StellarWarp/AutoDelegate/blob/aca3daab914712628bb76b68f6f09962dd91954d/src/delegate/function.h#L480-L487
析构自己是相当危险的，如果构造抛异常的话，很难在后续操作中避免未定义行为。
应该考虑下换成构造新对象然后与 `*this` 交换。

**但是！ `swap` 在哪？**

https://github.com/StellarWarp/AutoDelegate/blob/aca3daab914712628bb76b68f6f09962dd91954d/src/delegate/function.h#L204
https://github.com/StellarWarp/AutoDelegate/blob/aca3daab914712628bb76b68f6f09962dd91954d/src/delegate/function.h#L543
这里可能最好加 `explicit`，也可以考虑下一起加 `noexcept`。

**Comment by StellarWarp** [comment]
感谢建议，在 [9e54bbb](https://github.com/StellarWarp/AutoDelegate/commit/9e54bbb2326d642d3ae1431bab27bad98610d857) 中修复了
